# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NEST',
                'doc_host': 'https://plezar.github.io',
                'git_url': 'https://github.com/plezar/NEST',
                'lib_path': 'NEST'},
  'syms': {'NEST.core': {'NEST.core.foo': ('core.html#foo', 'NEST/core.py')}}}
