"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_labels.ipynb.

# %% auto 0
__all__ = ['predict', 'plot_outlines', 'get_physical_size', 'expand_with_cap', 'plot_label_mask', 'plot_channel_mask',
           'compute_mfi']

# %% ../nbs/02_labels.ipynb 3
import numpy as np
import tifffile
from cellpose import models, io
import matplotlib.pyplot as plt
from matplotlib import cm
from typing import Tuple
from skimage.segmentation import find_boundaries
from scipy.ndimage import distance_transform_edt
from skimage.segmentation import find_boundaries
from imageio import imwrite
import pandas as pd
from skimage.util import img_as_ubyte


def predict(
    img_list: list,
    use_gpu: bool,
    model_path: str = None,
    diameters: float = None,
    cellpose_param: tuple = (0.4, 0.0)
) -> np.ndarray:
    """
    Run a Cellpose segmentation model to generate segmentation masks for a list of images.

    This function loads a Cellpose model and applies it to each image in the provided list.
    If a custom model path is given, it uses that pretrained model; otherwise, it defaults to the
    nuclei segmentation model. The segmentation thresholds can be controlled via cellpose_param,
    and an estimated diameter of the objects (nuclei) to segment can be provided when using the default model.

    Parameters
    ----------
    img_list : list of np.ndarray
        A list of image arrays (grayscale) to segment.
    use_gpu : bool
        Indicates whether to use GPU acceleration for model evaluation.
    model_path : str, optional
        Path to a custom pretrained Cellpose model. If None, the default nuclei model is used.
    diameters : float, optional
        Estimated diameter (in pixels) of the objects (nuclei) to segment. This is used only when model_path is None.
    cellpose_param : tuple of two floats, optional
        A tuple (flow_threshold, cellprob_threshold) to control the Cellpose evaluation parameters.
        Defaults to (0.4, 0.0).

    Returns
    -------
    np.ndarray
        Array of shape (N, H, W) containing the segmentation masks for each input image.
    """
    if model_path:
        model = models.CellposeModel(
            gpu=use_gpu,
            pretrained_model=model_path
        )
        print(f"Using custom Cellpose model from {model_path} for segmentation.")
        mask, flow, style = model.eval(
            list(img_list),
            flow_threshold=cellpose_param[0],
            cellprob_threshold=cellpose_param[1],
            channels=[0, 0]
        )
    else:
        model = models.Cellpose(gpu=use_gpu, model_type='nuclei')
        print("Using default Cellpose model for nuclei segmentation.")
        mask, diams, flow, style = model.eval(
            list(img_list),
            flow_threshold=cellpose_param[0],
            cellprob_threshold=cellpose_param[1],
            diameter=diameters,
            channels=[0, 0]
        )

    return mask


def plot_outlines(
    mask: np.ndarray,
    image: np.ndarray,
    save_path: str = None
):
    """
    Overlay nuclear outlines from a mask onto an image and optionally save the result.

    Parameters
    ----------
    mask : np.ndarray
        2D array of integer labels where nonzero values indicate nuclei.
    image : np.ndarray
        Grayscale image array of the same shape as `mask`.
    save_path : str, optional
        File path in which to save the outline image. If None, no file is written.

    Returns
    -------
    fig : matplotlib.figure.Figure
        Figure object containing the outline overlay.
    ax : matplotlib.axes.Axes
        Axes object displaying the overlay.
    """
    image = img_as_ubyte(image)
    boundaries = find_boundaries(mask, mode='outer')
    outline_image = np.zeros_like(mask, dtype=np.uint8)
    outline_image[boundaries] = 255

    h, w = mask.shape
    green = np.zeros((h, w), dtype=np.uint8)
    stacked = np.stack([outline_image, green, image], axis=-1)

    if save_path:
        imwrite(save_path, stacked)

    return stacked


def get_physical_size(
    filename: str,
    verbose: bool = False) -> float:
    """
    Compute the physical pixel size (µm/px) from a TIFF file's resolution metadata.

    Parameters
    ----------
    filename : str
        Path to the TIFF file.
    verbose : bool, optional
        If True, print resolution details. Default is False.

    Returns
    -------
    px_um : float
        Physical size of a pixel in microns. Raises if pixels are non-square.
    """

    with tifffile.TiffFile(filename) as tif:
        page = tif.pages[0]

        rx_num, rx_den = page.tags['XResolution'].value
        ry_num, ry_den = page.tags['YResolution'].value

        um_per_unit = 1

        px_per_unit_x = rx_num / rx_den
        px_per_unit_y = ry_num / ry_den

        px_w_um = um_per_unit / px_per_unit_x
        px_h_um = um_per_unit / px_per_unit_y

        width = page.imagewidth
        height = page.imagelength

        if verbose:
            #print(f"ResolutionUnit code: {unit_code}")
            print(f"Pixel size = {px_w_um:.3f} × {px_h_um:.3f} µm/px")
            print(f"Physical size = {width * px_w_um:.1f} × {height * px_h_um:.1f} µm")

        if px_h_um == px_w_um:
            return px_h_um
        else:
            raise ValueError("Pixel height and width are not the same")


def expand_with_cap(
    label_image: np.ndarray,
    spacing: Tuple[float, float],
    fixed_expand: float = 10.0,
    max_area_ratio: float = 1.5
) -> np.ndarray:
    """
    Expand labeled nuclei by up to a fixed radius, capped by max area ratio.

    Parameters
    ----------
    label_image : np.ndarray
        2D integer array of labels (0=background).
    spacing : tuple of float
        Physical size (µm) of each pixel along (row, column) axes.
    fixed_expand : float, optional
        Nominal expansion radius in µm. Default is 10.0.
    max_area_ratio : float, optional
        Maximum allowed area increase factor. Default is 1.5.

    Returns
    -------
    labels_out : np.ndarray
        Dilated label image, where each pixel is assigned to the nearest
        original label if within its per-pixel cap.
    """
    pixel_area = np.prod(spacing)
    labels = np.unique(label_image)
    labels = labels[labels != 0]
    r0 = {lbl: np.sqrt((np.sum(label_image == lbl) * pixel_area) / np.pi)
          for lbl in labels}

    factor = np.sqrt(max_area_ratio) - 1.0
    d_max = {lbl: factor * r0[lbl] for lbl in labels}

    max_lbl = int(label_image.max())
    d_max_arr = np.zeros(max_lbl + 1, dtype=float)
    for lbl, dm in d_max.items():
        d_max_arr[lbl] = dm

    distances, nearest_coords = distance_transform_edt(
        label_image == 0,
        sampling=spacing,
        return_indices=True
    )
    nearest_lbls = label_image[tuple(nearest_coords)]

    per_pixel_cap = np.minimum(fixed_expand, d_max_arr[nearest_lbls])
    dilate_mask = distances <= per_pixel_cap

    labels_out = np.zeros_like(label_image)
    labels_out[dilate_mask] = nearest_lbls[dilate_mask]
    
    return labels_out

def plot_label_mask(mask,
                    cell_type_map=None,
                    type_colors=None,
                    default_color=(0, 0, 0),
                    outline_color='black',
                    seed=None,
                    save_path=None,
                    nuclear_mask=None):
    """
    Plot a label mask coloring cells based on their assigned type.
    Unspecified or 'other' cells remain in default_color (black by default).
    Adds outlines for both cell and nuclear masks in specified color.

    Parameters:
    -----------
    mask : 2D int array
        Label mask where 0 is background and positive integers denote cell IDs.
    cell_type_map : dict or None
        Mapping from cell label (int) to cell type name (str).
    type_colors : dict or None
        Mapping from cell type name (str) to RGB tuple (floats 0-1).
        If None, random distinct colors will be generated for each type.
    default_color : tuple of 3 floats
        RGB color for cells not in cell_type_map or not in type_colors.
    outline_color : str or tuple
        Color for outlines. Accepts 'black', 'white', or an RGB tuple (floats 0–1).
    seed : int or None
        Random seed for reproducible color assignment.
    save_path : str or None
        If provided, path to save the plotted RGB image.
    nuclear_mask : 2D array of ints or bool, optional
        Nuclear segmentation mask to overlay as outlines.
    """
    # parse outline_color
    if isinstance(outline_color, str):
        if outline_color.lower() == 'black':
            oc_rgb = (0, 0, 0)
        elif outline_color.lower() == 'white':
            oc_rgb = (1, 1, 1)
        else:
            raise ValueError("outline_color must be 'black', 'white', or an RGB tuple")
    else:
        oc_rgb = outline_color

    # determine which labels to color
    labels = np.unique(mask)
    labels = labels[labels != 0]

    # map each label to a type string
    if cell_type_map is not None:
        lbl_to_type = {lbl: cell_type_map.get(lbl, "other") for lbl in labels}
        types = sorted(set(lbl_to_type.values()))
    else:
        lbl_to_type = {lbl: "type" for lbl in labels}
        types = ["type"]

    # assign colors to each type
    if type_colors is None:
        rng = np.random.RandomState(seed)
        types_non_other = [t for t in types if t != "other"]
        random_colors = rng.rand(len(types_non_other), 3)
        type_colors = {t: tuple(c) for t, c in zip(types_non_other, random_colors)}
        type_colors["other"] = default_color
    else:
        type_colors = dict(type_colors)
        type_colors.setdefault("other", default_color)

    # build lookup table for label→RGB
    max_lbl = int(mask.max())
    lut = np.zeros((max_lbl + 1, 3), dtype=float)
    lut[0] = default_color  # background
    for lbl in labels:
        t = lbl_to_type.get(lbl, "other")
        lut[lbl] = type_colors.get(t, default_color)

    # apply LUT to get RGB image
    rgb = lut[mask]

    # overlay cell outlines
    cell_bound = find_boundaries(mask, mode='outer')
    rgb[cell_bound] = oc_rgb

    # overlay nuclear outlines if provided
    if nuclear_mask is not None:
        nuc_bound = find_boundaries(nuclear_mask, mode='outer')
        rgb[nuc_bound] = oc_rgb

    # plot
    fig, ax = plt.subplots()
    ax.imshow(rgb, interpolation='nearest')
    ax.axis('off')
    plt.tight_layout()

    # save if requested
    if save_path:
        imwrite(save_path, (rgb * 255).astype(np.uint8))

    plt.show()

def plot_channel_mask(mask, channel1, channel2=None, channel3=None, save_path=None, nuclear_mask=None):
    """
    Plot up to three fluorescence channels with cell and nuclear mask overlays.
    
    If only channel1 is provided, uses Spectral colormap.
    If channel2 and channel3 are provided, displays:
      - channel1 in green
      - channel2 in magenta
      - channel3 in yellow
    
    Parameters:
    -----------
    mask : 2D int array
        Label mask of cells (0=background).
    channel1 : 2D array
        First fluorescence channel.
    channel2 : 2D array or None
        Second fluorescence channel.
    channel3 : 2D array or None
        Third fluorescence channel.
    save_path : str or None
        Optional path to save resulting image.
    nuclear_mask : 2D array or None
        Nuclear segmentation mask for outlines.
    """
    # Normalize helper
    def normalize(img):
        img = img.astype(float)
        mn, mx = img.min(), img.max()
        return (img - mn) / (mx - mn) if mx > mn else np.zeros_like(img)
    
    # Prepare base RGB
    if channel2 is not None and channel3 is not None:
        # assume normalize() is defined as before
        c1 = normalize(channel1)
        c2 = normalize(channel2)
        c3 = normalize(channel3)

        # build an empty RGB image
        rgb = np.zeros(mask.shape + (3,), dtype=float)

        # channel1 → Green
        rgb[..., 1] = c1

        # channel2 → Red
        rgb[..., 0] = c2

        # channel3 → Blue
        rgb[..., 2] = c3
    else:
        # Single channel: use Spectral colormap
        img_norm = normalize(channel1)
        cmap = plt.get_cmap('Spectral').reversed()
        rgb = cmap(img_norm)[..., :3]
    
    # Mask background outside cells to black
    rgb[mask == 0] = 0
    
    # Overlay cell boundaries in white
    cell_bound = find_boundaries(mask, mode='outer')
    rgb[cell_bound] = [1, 1, 1]
    
    # Overlay nuclear boundaries in blue
    if nuclear_mask is not None:
        nuc_bound = find_boundaries(nuclear_mask, mode='outer')
        rgb[nuc_bound] = [0, 0, 1]
    
    # Display
    fig, ax = plt.subplots()
    ax.imshow(rgb, interpolation='nearest')
    ax.axis('off')
    plt.tight_layout()
    
    # Save if requested
    if save_path:
        imwrite(save_path, (rgb * 255).astype(np.uint8))
    
    plt.show()


def compute_mfi(cell_mask, channel1, channel2=None, channel3=None, nuclear_mask=None):
    """
    Fast computation of mean fluorescence intensity (MFI) per cell and per nucleus
    using vectorized numpy.bincount operations.

    Parameters
    ----------
    cell_mask : 2D int array
        Label mask of cells (0 = background).
    channel1 : 2D float array
        First fluorescence channel.
    channel2 : 2D float array, optional
        Second fluorescence channel.
    channel3 : 2D float array, optional
        Third fluorescence channel.
    nuclear_mask : 2D int array, optional
        Label mask of nuclei (0 = background). If provided, nuclei MFI is computed.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns:
         - region: 'cell' or 'nucleus'
         - label: integer label
         - mfi_ch1, mfi_ch2, mfi_ch3 (if provided)
    """
    records = []
    
    # Helper to compute sums and counts via bincount
    def _compute(label_mask, channels):
        flat_labels = label_mask.ravel()
        counts = np.bincount(flat_labels)
        results = {}
        for name, channel in channels.items():
            flat_chan = channel.ravel()
            sums = np.bincount(flat_labels, weights=flat_chan)
            # Avoid division by zero; only divide where counts>0
            mfi = np.zeros_like(sums, dtype=float)
            nonzero = counts > 0
            mfi[nonzero] = sums[nonzero] / counts[nonzero]
            results[name] = mfi
        return counts, results

    # Channels dict
    channels = {'mfi_ch1': channel1}
    if channel2 is not None:
        channels['mfi_ch2'] = channel2
    if channel3 is not None:
        channels['mfi_ch3'] = channel3

    # Compute for cells
    counts_cell, mfi_cell = _compute(cell_mask, channels)
    cell_labels = np.unique(cell_mask)
    cell_labels = cell_labels[cell_labels != 0]

    cell_data = {
        'region': ['cell'] * len(cell_labels),
        'label': cell_labels
    }
    for name, arr in mfi_cell.items():
        cell_data[name] = arr[cell_labels]

    df = pd.DataFrame(cell_data)

    # Compute for nuclei if provided
    if nuclear_mask is not None:
        counts_nuc, mfi_nuc = _compute(nuclear_mask, channels)
        nuc_labels = np.unique(nuclear_mask)
        nuc_labels = nuc_labels[nuc_labels != 0]
        nuc_data = {
            'region': ['nucleus'] * len(nuc_labels),
            'label': nuc_labels
        }
        for name, arr in mfi_nuc.items():
            nuc_data[name] = arr[nuc_labels]
        df_nuc = pd.DataFrame(nuc_data)
        df = pd.concat([df, df_nuc], ignore_index=True)

    return df
