"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_preprocess.ipynb.

# %% auto 0
__all__ = ['clahe']

# %% ../nbs/00_preprocess.ipynb 3
from skimage.segmentation import find_boundaries, expand_labels
from imageio import imwrite
import cv2
from typing import Tuple
from scipy.optimize import linear_sum_assignment
from scipy.ndimage import distance_transform_edt
import numpy as np

# %% ../nbs/00_preprocess.ipynb 4
def clahe(
    image: np.ndarray,
    clip_limit: float,
    tile_grid_size: Tuple[int, int]
) -> np.ndarray:
    """
    Apply Contrast Limited Adaptive Histogram Equalization (CLAHE) to a grayscale image.

    Parameters
    ----------
    image : np.ndarray
        2D array representing the input grayscale image.
    clip_limit : float
        Threshold for contrast limiting. Higher values result in stronger contrast enhancement.
    tile_grid_size : tuple of int
        Size (height, width) of the grid for histogram equalization (e.g., (8, 8)).

    Returns
    -------
    np.ndarray
        CLAHE-enhanced image as a 2D array.
    """
    clahe = cv2.createCLAHE(
        clipLimit=clip_limit,
        tileGridSize=tile_grid_size
    )
    return clahe.apply(image)
